import os
import os.path
import write.condefine as cf
import config as conf

def insertsqlformat ( listtotal ,f1):
	#insert
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlinsert)
	liststr.append(" ")
	liststr.append(cf.xmlid)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlinsert)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(" ")
	liststr.append(cf.xmlsqlparameterType)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(conf.packagetxt)
	liststr.append(cf.xmlmodel)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	
	liststr = []
	liststr.append(cf.xmlinsert)
	liststr.append(" ")
	liststr.append(cf.xmlinto)
	liststr.append(" ")
	liststr.append(cf.classnamebefore)
	liststr.append(cf.xmllsq)
	liststr.append('\n')
	liststr.append('\t\t\t')
	for x in listtotal:
		liststr.append(x[1])
		liststr.append(',')
	liststr.pop()
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlrsq)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlvalues)
	liststr.append(cf.xmllsq)
	liststr.append('\n')
	liststr.append('\t\t\t')
	for x in listtotal:
		if x[2] != 'TIMESTAMP':
			liststr.append("#{"+ x[1]+ "}")
			liststr.append(',')
		else:
			liststr.append("to_timestamp(#{"+ x[1]+ "},'yyyy-MM-dd HH24:mi:ss')")
			liststr.append(',')
	liststr.pop()
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.endtablestr)
	str = "\t\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlinsert)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')

def updatesqlformat ( listtotal ,f1):
	#update
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlupdate)
	liststr.append(" ")
	liststr.append(cf.xmlid)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlupdate)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(" ")
	liststr.append(cf.xmlsqlparameterType)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(conf.packagetxt)
	liststr.append(cf.xmlmodel)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	liststr = []
	liststr.append(cf.xmlupdate)
	liststr.append(" ")
	liststr.append(cf.classnamebefore)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlset)
	liststr.append(cf.xmlright)
	for x in listtotal:
		liststr.append('\n')
		liststr.append('\t\t\t')
		liststr.append(cf.xmlleft)
		liststr.append(cf.xmlif)
		liststr.append(" ")
		liststr.append(cf.xmltest)
		liststr.append(cf.xmlequ)
		liststr.append(cf.xmllm)
		liststr.append(cf.xmlitem+".")
		liststr.append(x[0])
		liststr.append(cf.xmlnot1)
		liststr.append(cf.xmllm)
		liststr.append(cf.xmlright)
		liststr.append(x[1])
		if x[2] != 'TIMESTAMP':
			liststr.append("=#{"+conf.xmlitem+"."+x[0]+"},")
		else:
			liststr.append("=to_timestamp(#{"+conf.xmlitem+"."+x[0]+"},'yyyy-MM-dd HH24:mi:ss')")
		liststr.append(cf.xmlleft)
		liststr.append(cf.xmlend)
		liststr.append(cf.xmlif)
		liststr.append(cf.xmlright)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlset)
	liststr.append(cf.xmlright)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlwhere)
	liststr.append(" ")
	liststr.append(listtotal[0][1])
	liststr.append(" ")
	liststr.append(cf.xmlequ)
	liststr.append("#{"+conf.xmlitem+"."+listtotal[0][0]+"},")
	str = "\t\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlupdate)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')
	
def deletesqlformat ( listtotal ,f1):
	#delete
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmldelete)
	liststr.append(" ")
	liststr.append(cf.xmlid)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmldelete)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	liststr = []
	liststr.append(cf.xmldelete)
	liststr.append(" ")
	liststr.append(cf.xmlfrom)
	liststr.append(" ")
	liststr.append(cf.classnamebefore)
	liststr.append(" ")
	liststr.append(cf.xmlwhere)
	liststr.append(" ")
	liststr.append(listtotal[0][1])
	liststr.append(" ")
	liststr.append(cf.xmlin)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlforeach + " ")
	liststr.append('collection="array" index="index" item="item" open="(" separator="," close=")"')
	liststr.append(cf.xmlright)
	liststr.append('\n')
	liststr.append('\t\t\t')
	liststr.append("#{"+conf.xmlitem +"}")
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlforeach)
	liststr.append(cf.xmlright)
	str = "\t\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmldelete)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')

def getsqlformat ( listtotal ,f1):
	#get
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlselect)
	liststr.append(" ")
	liststr.append(cf.xmlid)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlselect)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(" ")
	liststr.append(cf.xmlresultType)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(conf.packagetxt)
	liststr.append(cf.xmlmodel)
	liststr.append(cf.classname)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	
	liststr = []
	liststr.append(cf.xmlselect)
	for x in listtotal:
		liststr.append("\n")
		liststr.append("\t\t\t")
		liststr.append(x[1])
		liststr.append(" ")
		liststr.append(cf.xmlas)
		liststr.append(" ")
		liststr.append(x[0])
		liststr.append(',')
	liststr.pop()
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlfrom)
	liststr.append(" ")
	liststr.append(cf.classnamebefore)
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlwhere)
	liststr.append(" ")
	liststr.append("1=1")
	liststr.append('\n')
	liststr.append('\t\t')
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlif)
	liststr.append(" ")
	liststr.append(cf.xmltest)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(listtotal[0][0])
	liststr.append(cf.xmlnot1)
	liststr.append(cf.xmland)
	liststr.append(" ")
	liststr.append(listtotal[0][0])
	liststr.append(cf.xmlnot2)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	liststr.append('\n')
	liststr.append('\t\t\t')
	liststr.append(cf.xmland)
	liststr.append(" ")
	liststr.append(listtotal[0][1])
	liststr.append(cf.xmlequ)
	liststr.append("#{"+listtotal[0][0]+"}")
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlif)
	liststr.append(cf.xmlright)
	str = "\t\t" + ''.join(liststr)
	f1.write(str + '\n')
	
	
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlselect)
	liststr.append(cf.xmlright)
	str = "\t" + ''.join(liststr)
	f1.write(str + '\n')

def xmlwrite (listtotal):
	path = 'java\\'+cf.classname+'\\' +cf.classname+ cf.xmlfile
	isExists=os.path.exists(path)
	if not isExists:
		print (path+' 创建成功')
	else:
		print (path+' 目录已存在')
		f = open('java\\'+ cf.classname+'\\' +cf.classname+ cf.xmlfile,"r+")
		read_data = f.read()
		f.seek(0)
		f.truncate()
		f.close()
	f1 = open('java\\'+ cf.classname+'\\' + cf.classname + cf.xmlfile,'a') 
	for x in cf.xmlline:
		f1.write (x + '\n')
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlmapper)
	liststr.append(cf.xmlnamespace)
	liststr.append(cf.xmlequ)
	liststr.append(cf.xmllm)
	liststr.append(conf.packagetxt)
	liststr.append(cf.xmldao)
	liststr.append(cf.classname)
	liststr.append(cf.xmlDao)
	liststr.append(cf.xmllm)
	liststr.append(cf.xmlright)
	str = ''.join(liststr)
	f1.write(str + '\n')
	
	insertsqlformat ( listtotal ,f1)
	
	updatesqlformat ( listtotal ,f1)
	
	deletesqlformat ( listtotal ,f1)
	
	getsqlformat ( listtotal ,f1)
	
	
	
	liststr = []
	liststr.append(cf.xmlleft)
	liststr.append(cf.xmlend)
	liststr.append(cf.xmlmapper)
	liststr.append(cf.xmlright)
	str = ''.join(liststr)
	f1.write(str + '\n')
	
	f1.close()